apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-c4hq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-c4hq@sha256:0356a730774efaab275e6413b4218b51900262b34fbb0592c9695ac077de8a4a
        name: my-nodejs
        resources: {}
status: {}
